export class ViewOrderSections {
  static MY_CONFIRMED_SHIPPING_PORTAL = 1;
  static MY_CONFIRMED_SHIPPING_PARTNER = 2;
  static MY_CONFIRMED_CUSTOM_PORTAL = 3;
  static MY_CONFIRMED_CUSTOM_PARTNER = 4;
  static MY_CONFIRMED_PRODUCT_PORTAL = 5;
  static MY_CONFIRMED_PRODUCT_PARTNER = 6;
  static CLIENT_CONFIRMED_SHIPPING_PORTAL = 7;
  static CLIENT_CONFIRMED_SHIPPING_PARTNER = 8;
  static CLIENT_CONFIRMED_CUSTOM_PORTAL = 9;
  static CLIENT_CONFIRMED_CUSTOM_PARTNER = 10;
  static CLIENT_CONFIRMED_PRODUCT_PORTAL = 11;
  static CLIENT_CONFIRMED_PRODUCT_PARTNER = 12;

  static MY_PLACED_SHIPPING_SUPPLIER = 13;
  static MY_PLACED_SHIPPING_SUPPLIERS = 14;
  static MY_PLACED_CUSTOM_SUPPLIER = 15;
  static MY_PLACED_CUSTOM_SUPPLIERS = 16;
  static MY_PLACED_PRODUCT_SUPPLIER = 17;
  static MY_PLACED_PRODUCT_SUPPLIERS = 18;

  static CLIENT_PLACED_SHIPPING = 19;
  static CLIENT_PLACED_CUSTOM = 20;
  static CLIENT_PLACED_PRODUCT = 21;
}
